mysql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "password"
  options: "?useSSL=false&autoReconnect=true"

debug: true

motd:
  - "&5&lPulseMC"
  - "&fFaremos História em &6&l2025&f!"