mysql:
  host: br.asc.01.db.streethosting.com.br
  port: 3306
  database: s30_lobby
  username: u30_ty6YXPeydy
  password: KLsN^E=6HgJUSnulvDDUv^zL
  options: ?useSSL=false&autoReconnect=true

redis:
  host: br-asc-01.streethosting.com.br
  port: 25567
  password: fodase23123

debug: true

format-messages: '%leaftags_tag_prefix% {PLAYER-NAME} &7» &f{MESSAGE}'

lobby-itens:
  # Exemplo
  compass:
    # 0-8
    slot: 0
    # Se for SKULL_ITEM e data: 3, retorna a cabeça do jogador
    material: COMPASS
    data: 0
    glow: false
    command: dm open minigames
  duels:
    slot: 4
    material: BLAZE_ROD
    data: 0
    glow: false
    commando: duels desafiar {TARGET}