name: Lobby
author: tadeu
softdepend: [ TAB, PlaceholderAPI]
version: '${project.version}'
main: br.com.pulsemc.minecraft.lobby.Main
commands:
  language:
    aliases: [idioma, linguagem]
  setlobby:
  build: